### ISSUE TITLE
Intellisense from node_modules?

### ISSUE THREAD

**Issue by tomasvn** [wkillerud/vscode-scss#36]
https://github.com/mrmlnc/vscode-scss/issues/41#issuecomment-600561702

Is is possible to have intellisense for defined node_modules path? I am using a 3rd party library, but I can't seem to make it work. @wkillerud

**Comment by wkillerud** [comment]
You can have IntelliSense for files from `node_modules`  as long as they are included with `@use` from a file inside your project.

Can you make a GitHub repo that shows your problem @tomasvn?

**Comment by tomasvn** [comment]
Cannot make a minimal repo, as this package is a private package. But the problem is we have is a eg. ui package `@company/design-system` 

and in gulp sass we are calling `sass.sync` with the `includePaths` property, but calling use or import is not giving suggest

```
node_modules

@company/
├─ design-system/
│  ├─ dist/
│  │  ├─ css/
│  │  │  ├─ colors.scss

```

**Comment by wkillerud** [comment]
So what you're after is suggestions to complete the `@use` statement itself?  Say you write `@use "@company/desi` you want autocomplete/suggestions for `@use "@company/design-system/dist/css/colors";`?

**Comment by tomasvn** [comment]
Yes basically. And when I ctr + click on the path it would show correct reference, list of all defined color variables. And when using eg. `$bas` -> autocomplete/suggestions -> it will know I want to use `$base-color` which is from the `@use "@company/design-system/dist/css/colors";`

**Comment by tomasvn** [comment]
If I have those files locally, where we are transpiling scss to css it works right, I have my master file eg. `app.scss` in folder components and also here I could have `btn.scss` and if I would do `@import ./` now autocomplete would show `@import ./btn;`

**Comment by wkillerud** [comment]
#40 will add some code completion to make it easier to import from `node_modules`.

I made a new issue to look into `includePaths` (#41). I suspect that's the main problem you're having.

For now, you need to either:

- Use relative imports (`@use "../path/to/file";`).
- Import from a package in `node_modules` (`@use "@myorg/package/path/to/file";`, assuming `node_modules/@myorg/package` exists).
