### ISSUE TITLE
Intellisense for css variables

### ISSUE THREAD

**Issue by tomasvn** [wkillerud/vscode-scss#37]
Is it possible to get Intellisense for css variables? Without me defining scss variable to hold css variable inside @wkillerud 

I dont want to install extra extension such as https://marketplace.visualstudio.com/items?itemName=vunguyentuan.vscode-css-variables just to get some intellisense

**Comment by wkillerud** [comment]
CSS variables is not something I'm going to prioritize. That's the responsibility of the CSS language server, or extensions like the one you link to.
