### ISSUE TITLE
improvements to placeholder selectors

### ISSUE THREAD

**Issue by KraXen72** [wkillerud/vscode-scss#49]
- when typing `%`, you have to hit `Ctrl` + `Space` to manually bring up autocompletion, whereas typing `.` (for class) already pops up the autocompletion. not sure if this is something you can control from the extension or it's user settings based
    - however, typing anything after the % gives completions, so it's pretty good
- only defined placeholders get autocompleted - a pretty common use for placeholders (atleast in discord css theming) is to assign a bunch of non-existent placeholders to discord's classes, like this:
```scss
.app-3xd6d0 {
  @extend %app !optional;
}
.app-2CXKsg {
  @extend %shakeable !optional;
}
.bg-1QIAus {
  @extend %bg !optional;
}
.layers-OrUESM {
  @extend %layers !optional;
}
.layer-86YKbF {
  @extend %layer !optional;
}
.animating-1rIrGV {
  @extend %layerAnimating !optional;
}
```
- once you define a placeholder, for example `%shakeable` in your project somewhere, the class gets it applied properly, due to this [mapping file](https://github.com/ClearVision/ClearVision-v6/blob/master/lib/selectors/selectorPlaceholders.scss) all of the other classes only optionally extend selectors, so they won't get included in the final theme, making the css only as big as it needs to be.
- this is because discord often changes the class names, and this way they only need to be updated in one place in the theme.
i would like an option in the extension, to also autocomplete referenced & undefined placeholders, like these.

**Comment by KraXen72** [comment]
i understand if this is a pretty niche use case, but it would be super awesome to have this working, because:
1) there are a lot of selectors in this file, and manually searching them is pain
2) all of the other vs code extensions for scss i tried don't even have placeholder support, and also don't have referenced placeholder support
3) i would be very thankful if it was implemented :)))

**Comment by wkillerud** [comment]
Just so I understand the workflow:

- A third party stylesheet `A` is written using placeholder selectors, like `.bg-1QIAus { @extend %bg !optional; }`
- You the developer write a stylesheet `B`, which essentially is the _implementation_ of the placeholder selectors.

In other words, your stylesheet/workflow consist mostly of:

```scss
%app {
  font-family: "Comic Sans", sans-serif;
}

%bg {
  background: limegreen;
}

%|  /* would like completions for other potential placeholders here */
```

**Comment by wkillerud** [comment]
> when typing %, you have to hit Ctrl + Space to manually bring up autocompletion

Ah, forgot to test that 😄 Hang tight, #50 is on the way.

**Comment by wkillerud** [comment]
Another question, how does stylesheet `A` from above (the Discord classes) get access to the placeholder selectors you write? An example repo would be helpful.

**Comment by KraXen72** [comment]
https://github.com/KraXen72/rosebox/tree/discord-rewrite-v/discord

**Comment by KraXen72** [comment]
> Just so I understand the workflow:
> 
> * A third party stylesheet `A` is written using placeholder selectors, like `.bg-1QIAus { @extend %bg !optional; }`
> * You the developer write a stylesheet `B`, which essentially is the _implementation_ of the placeholder selectors.
> 
> In other words, your stylesheet/workflow consist mostly of:
> 
> ```css-scss
> %app {
>   font-family: "Comic Sans", sans-serif;
> }
> 
> %bg {
>   background: limegreen;
> }
> 
> %|  /* would like completions for other potential placeholders here */
> ```

yes. i have a script that downloads the third-party stylesheet into a `lib/` folder so other partial files can access it (everything is imported in `main.scss`)

**Comment by KraXen72** [comment]
the distribution of that external stylesheet is not really standardized, i just fetch it with `node-fetch` and include it's licence in the same folder. no idea how others do it but i am not going to do it manually every time lol. many discord css makers use just plain css & classes but then they have to patch it a lot. i've seen several other people who use scss like me use these placeholders.

**Comment by KraXen72** [comment]
also, you should add placeholder support in the extension readme, it's one of the few if not only scss extension that supports them, so you should be proud about it :))))

**Comment by wkillerud** [comment]
Thank you for the example repo :) 

I have an idea on how to solve this. Some notes:

- extend the [parser](https://github.com/wkillerud/vscode-scss/blob/main/server/src/parser/parser.ts) to also look for _usages_ of placeholders
- track those usages in each [ScssDocument](https://github.com/wkillerud/vscode-scss/blob/main/server/src/parser/scss-document.ts) in a new `Map`
- extend the [completion context](https://github.com/wkillerud/vscode-scss/blob/main/server/src/features/completion/completion-context.ts) to recognize when we're writing a placeholder _declaration_
  - Either `/^%/`, or `/\s+%/` where [`textBeforeWord`](https://github.com/wkillerud/vscode-scss/blob/46470d95d1de92c21877cac6f9b4dfe534e68676/server/src/features/completion/completion-context.ts#L134) does not include `@extend`.
- if in such a context, in [`completion`](https://github.com/wkillerud/vscode-scss/blob/46470d95d1de92c21877cac6f9b4dfe534e68676/server/src/features/completion/completion.ts#L102), loop through all `scssDocument` in `storage` and generate a suggestion from the tracked placeholder _usages_

That implementation should get us most of the way there, without adding too much complexity. One potential improvement for the future:

- be smart about imports, and only build suggestions based on what files are importing the one currently being edited

This week and weekend is busy, but I might work on this sometime in May. Seems like a fun problem to solve :)

**Comment by KraXen72** [comment]
thanks for the notes. if i have some time, i might take a look at it, but i am also quite busy currently.

**Comment by wkillerud** [comment]
My weekend opened up, so I got to this sooner than expected. Should be out now, [version `2.12.0`](https://github.com/wkillerud/vscode-scss/releases/tag/2.12.0).

Thanks a bunch for the input on this. It's made me appreciate this part of the language much more 😄

**Comment by KraXen72** [comment]
i'm glad i could provide some input. you're incredible for implementing this & implementing this so quickly. thank you so much.
