### ISSUE TITLE
autocomplete for referenced placeholder selectors issues

### ISSUE THREAD

**Issue by KraXen72** [wkillerud/vscode-scss#55]
- VS Code Version: 1.78.1
- SCSS IntelliSense Version: latest published by 29.4.2023 (idk version number, this is what shows in vscode ext readme)
- Operating System: win10

## the issue:
- autocomplete for reference selectors only occurs after manually triggering it with ctrl+space. ie,
- if you start typing `%chat` and a placeholder selector `%chatSearch` is referenced
    - you do not get autocomplete
    - even after manually triggering the autocomplete with `ctrl` + `space`, it has no suggestions
  
![Capture_2023_m05 d11_14;59](https://github.com/wkillerud/vscode-scss/assets/21956756/0061468a-8f48-4c1f-a7d4-7ffea8de021d)
![Capture_2023_m05 d11_14;59 (2)](https://github.com/wkillerud/vscode-scss/assets/21956756/d8d50cf8-6e77-428a-b34b-8a4f9ed072d6)
  
- only way to get autocomplete is typing `%`, then hitting `ctrl` + `space`,
  
![image](https://github.com/wkillerud/vscode-scss/assets/21956756/175ab75b-1d85-46e7-874d-ec2dc718ce6b)

## related issue 2:
in this autocomplete (that was manually triggered), each selector is listed twice:
![image](https://github.com/wkillerud/vscode-scss/assets/21956756/74324802-561f-44ec-b093-1a912f730c2b)
(show more does not do anything).
i thought this might be caused by some other sass extension, but i could not find any other sass/scss extension that supported placeholder selectors (nor did this work before your placeholderSelector update)
![image](https://github.com/wkillerud/vscode-scss/assets/21956756/f7ef87a9-0486-4708-a15d-908dbc420d5b)
  
## repro repo:
https://github.com/KraXen72/rosebox/tree/discord-rewrite-v, open the `discord` folder in vs code

**Comment by wkillerud** [comment]
> each selector is listed twice

That behavior is intentional. The second suggestion includes `{ }` with newline, indent, and moves the cursor inside the selector block. If you find them distracting, I could add an option to choose which one you want (with `{ }`, without, or both).

> only way to get autocomplete is typing %, then hitting ctrl + space

That's odd, I thought I fixed that in #50.

I can look into it, but it'll probably be a little while because of Tears of the Kingdom 😄

**Comment by wkillerud** [comment]
I tested today on Windows 11 (closest I can get to your setup).

- Code version 1.78.2
- Extension version 2.12.0 (visible after the title, top right on the extension page)


![](https://github.com/wkillerud/vscode-scss/assets/1223410/af1cfc66-3457-44c9-80e3-8ca29c1ccd93)

On my setup, I get suggestions immediately when typing `%`. Default settings for the extension. I don't know what may cause them to not appear for you. If you want, you can try [creating an empty profile](https://code.visualstudio.com/docs/editor/profiles) with default settings, install only Some Sass, and see if the same thing happens.

https://github.com/wkillerud/vscode-scss/assets/1223410/ea9c88c8-2a4c-499c-a40d-87285d9b8dc6


I _can_ reproduce the problem of no suggestions when hitting ctrl+space after, say, `%chat`. I'll look into a fix for that.

**Comment by wkillerud** [comment]
I published a bugfix for the `%chat` `ctrl+space` scenario, and added a setting (Suggestion Style) if you'd like to turn off the `{ }` suggestions. [Version 2.13.0](https://github.com/wkillerud/vscode-scss/releases/tag/2.13.0), PR #56.

**Comment by KraXen72** [comment]
thanks. also, unrelated, but how did you get that search bar on top of vs code? i don't have that

**Comment by wkillerud** [comment]
> how did you get that search bar on top of vs code?

That's the [command center](https://code.visualstudio.com/updates/v1_69#_command-center) setting.
