### ISSUE TITLE
Name collision between different modules when choosing which documentation to show in tooltip

### ISSUE THREAD

**Issue by rjgotten** [wkillerud/vscode-scss#63]
First off; great work on picking up the pieces and continuing where SCSS Intellisense left off.
This revised extension actually works well with `@use` where basically everything else, well ... bombs.

There's still one rather annoying bug with it though:
When you `@use` a function that collides with one of the built-in modules, the documentation for the built-in module is used.

E.g. if I make a custom module that exports a `get` function.
And I `@use` both that module and the built-in one...

![image](https://github.com/wkillerud/vscode-scss/assets/442808/f1dcec2d-f5a8-4438-912c-3ef048c35fa3)

That's obviously incorrect.
Is the extension maybe not checking from which namespace the token in question is being taken?

[EDIT]
Commenting out the `@use` for `sass:map` in this example doesn't fix it.
Maybe the documentation to show for built-in modules is a bit too eager then; and is not checking that something actually came from the built-in module?

**Comment by wkillerud** [comment]
Thanks for the bug report! Should be fixed in [2.14.1](https://github.com/wkillerud/vscode-scss/releases/tag/2.14.1).

**Comment by rjgotten** [comment]
@wkillerud 
Sorry- 2.14.1 seems to break import of SassDoc references and autocompletion suggestions completely.
Not even CTRL+Space explicit requests for completions brings them back up.

Reverting to 2.14.0 (and fully restarting VSCode - not just reloading with the 'reload required' button) brings them back.
Probably has something to do with how the extension works w/ the language service, as per: https://github.com/wkillerud/vscode-scss/issues/60#issuecomment-1685230200 - I'd wager.

**Comment by wkillerud** [comment]
> Sorry- 2.14.1 seems to break import of SassDoc references and autocompletion suggestions completely.
> Not even CTRL+Space explicit requests for completions brings them back up.

Can you do a screen recording of what isn't working @rjgotten, or be more specific? The things I've tested manually so far[^1] work as before, and all the automated tests are passing.


https://github.com/wkillerud/vscode-scss/assets/1223410/dbf6305b-c794-407f-a103-1ad98c60a039



[^1]: Hover info with SassDoc, Code suggestions, Code navigation
