### ISSUE TITLE
Intellisense in <style lang="scss">

### ISSUE THREAD

**Issue by jegwastaken** [wkillerud/vscode-scss#75]
Intellisense works in `.scss` files, but not in `scss` style blocks.

`app.scss` Intellisense works fine.

```scss
@use 'some_package_in_node_modules/mixins';

mixins.dostuff(); 
```

`file.svelte` Intellisense doesn't work.

```svelte
<style lang="scss">
    @use 'some_package_in_node_modules/mixins';

    mixins.dostuff(); 
</style>
```

Am I missing a setting or something? Is this use case not supported? Thanks in advance.

**Comment by Deemoguse** [comment]
Maybe you mean this?
```scss
@use 'some_package_in_node_modules/mixins';

@include mixins.dostuff(); 
```

You miss the `@include` at-rule

**Comment by jegwastaken** [comment]
No. Sorry, that was a (stupid) typo. I typed the code here instead of copying from my editor. `@include` is in the actual code and intellisense still doesn't work. It works fine in `.scss` files.

**Comment by wkillerud** [comment]
If that's the case you need to share a repo with code that demonstrates the problem. Like I said, it worked with my manual testing and the automated integration tests for Svelte files.
