### ISSUE TITLE
Missing dollar sign after autocompleting variables in Svelte

### ISSUE THREAD

**Issue by monkeyroar** [wkillerud/vscode-scss#97]
- VS Code version: 1.85.2 (Universal)
- Extension version: v2.14.6
- Operating system: macOS 14.2.1

When selecting variables from autocomplete suggestions after pressing '$' in `<style lang="scss">` tag of Svelte components, extension removes the '$' sign before variable name

![image](https://github.com/wkillerud/vscode-scss/assets/95053773/c31be6f0-c41c-4289-98a7-fa4c400543d2)
![image](https://github.com/wkillerud/vscode-scss/assets/95053773/dc289016-1c83-4f0d-b8eb-a65820171be6)

Steps to Reproduce:

1. Open .svelte file
2. Open `<style lang="scss">` tag
3. Press $
4. Select a variable from dropdown

**Comment by wkillerud** [comment]
Thanks for opening an issue 👍 

It used to be the case we ended up with double dollar signs in Svelte, Vue and Astro, so there's special handling of that in the extension. I can reproduce the bug you're seeing, so looks like that special handling is no longer needed for Svelte 🥳 Confirmed it's still needed for Vue and Astro though.

Fix should be ready soon.

**Comment by monkeyroar** [comment]
Hey, thanks for a great fix in such short time! I also noticed that when autocompleting function like `math.floor` there appears a second dot, could it be related somehow& Again, only reproducible in `<style lang="scss">` in Svelte

**Comment by wkillerud** [comment]
Good catch @monkeyroar, the double dot problem should be fixed in [2.14.8](https://github.com/wkillerud/vscode-scss/releases/tag/2.14.8).
